services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: edu-analytics-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PYTHONPATH: /app
    ports:
      - "8080:8080"
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/alembic:/app/alembic
      - ./pyproject.toml:/app/pyproject.toml
      - ./parser/storage:/app/parser/storage
    networks:
      - edu-net

  postgres:
    image: postgres:16
    container_name: edu-analytics-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edu-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-edu_user} -d ${POSTGRES_DB:-edu_analytics}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

#  frontend:
#    build: ./frontend
#    container_name: edu-analytics-frontend
#    depends_on:
#      - backend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    networks:
#      - edu-net
#    environment:
#      REACT_APP_API_URL: http://backend:8000/api/v1
#
#  ml:
#    build:
#      context: .
#      dockerfile: ./ml/Dockerfile
#    container_name: edu-analytics-ml
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: postgresql://${POSTGRES_USER:-edu_user}:${POSTGRES_PASSWORD:-edu_password}@postgres:5432/${POSTGRES_DB:-edu_analytics}
#    volumes:
#      - ./ml:/app/ml
#      - ./pyproject.toml:/app/pyproject.toml
#      - ml_data:/app/ml/data
#    networks:
#      - edu-net
#    command: python -m ml.training_pipeline
#
#  parser:
#    build:
#      context: .
#      dockerfile: ./parser/Dockerfile
#    container_name: edu-analytics-parser
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: postgresql://${POSTGRES_USER:-edu_user}:${POSTGRES_PASSWORD:-edu_password}@postgres:5432/${POSTGRES_DB:-edu_analytics}
#    volumes:
#      - ./parser:/app/parser
#      - ./pyproject.toml:/app/pyproject.toml
#    networks:
#      - edu-net
#    command: python parser/run.py

networks:
  edu-net:
    driver: bridge

volumes:
  postgres_data:
#    driver: local
#  ml_d
